// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// assign_type_from_lengths
CharacterVector assign_type_from_lengths(CharacterVector al_lens);
RcppExport SEXP _StoatPlot_assign_type_from_lengths(SEXP al_lensSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type al_lens(al_lensSEXP);
    rcpp_result_gen = Rcpp::wrap(assign_type_from_lengths(al_lens));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StoatPlot_assign_type_from_lengths", (DL_FUNC) &_StoatPlot_assign_type_from_lengths, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_StoatPlot(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
