# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Assign a variant type from ALLELE_LENGTHS field
#' @title Assign a variant type from ALLELE_LENGTHS field
#' @param al_lens a vector of allele lengths formatted as in ALLELE_LENGTHS, e.g. 1,0,10/56
#' @return a vector of characters with the variant types
#' @author Jean Monlong
#' @keywords internal
assign_type_from_lengths <- function(al_lens) {
    .Call(`_StoatPlot_assign_type_from_lengths`, al_lens)
}

